### ISSUE TITLE
H265: Non-decodable footage with AMF_VIDEO_ENCODER_HEVC_DE_BLOCKING_FILTER_DISABLE set to false

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#103]
When using HEVC encoding and keeping the Deblocking Filter enabled the encoder will produce footage that can't be decoded by strict decoders - it can still be decoded by less strict decoders and players.

### Files
* HevcDeBlockingFilter false: [2017-07-31 00-48-42.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/1186043/2017-07-31.00-48-42.zip)
* HevcDeBlockingFilter true: [2017-07-31 00-47-58.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/1186042/2017-07-31.00-47-58.zip) (Will look identical in anything but strict decoders)

**Comment by MikhailAMD** [comment]
Tested the file with:
- Windows Media Player on AMD and NV GPUs: plays OK
- Windows "Movies & TV" on AMD and NV GPUs: plays OK
- Latest VLC v2.2.6 with decode HW acceleration or not: plays OK 
- FFmpeg: transcodes OK
- Vega HEVC Analyzer from Interra: shows full compliance with  HEVC spec except double SPS/PPS NAL units which may be caused by extractor and do not affect the playback.
All points to a decoder in these tools.

**Comment by Xaymar** [comment]
This happens with strict decoders (Premiere Pro, After Effects, Vegas Pro). x265 content is played back fine by those.

**Comment by MikhailAMD** [comment]
"Strict" is a loose term. The stream either compliant with spec or not. So far we don't see any indication of non-compliance.

**Comment by Xaymar** [comment]
Have not heard back from either Sony or Adobe for this issue and it still seems to happen. Since the file is technically correct, I'll close this.
