### ISSUE TITLE
decoding several Videostreams (h264) in parallel

### ISSUE THREAD

**Issue by Findus79** [GPUOpen-LibrariesAndSDKs/AMF#128]
Whats the best practice for decoding more than one stream (h264) in parallel? One context per stream, or one context and just create one decoder/converter per stream running in seperate threads?

If I create two decoders in parallel (same context) I get "hiccups" (looks like the video jumps a few frames back every other second) in the decoded videos (running on a R270). Does not happen if I just decode a single video.

Thanks for any help or hints

**Comment by MikhailAMD** [comment]
It doesn't matter if an application uses one AMF context or many. It depends if the application wants to compose result of multiple decoding streams into one frame or not. If the app has to combine streams it has to share DX device between decoders and have output frames allocated in one device. If your app doesn't have to compose frames you may use different DX devices and different AMF contexts.
It both cases you may consider to synchronize decoder submissions for multiple streams to avoid the situation when the application submits several frames into one instance of decoder and because of HW decoder has a single HW queue, other instances have to wait. Consider that the app submits frames from diffrent threads. Then it may be a situation when HW queue looks like  D1,D1,D1,D1,D1,D2. If the app needs D2 it will wait for all D1 to be decoded. If the app adds pacing then submission will be always D1,D2,D1,D2,D1,D2. Note that the wait happens when decoded surface is actually used.
There is an AMF sample which implements paced submission to decoders for 360 stitching. Check StitchPipelineBase.cpp, use of class DecoderSubmissionSync.

**Comment by Findus79** [comment]
Thanks for the heads up, I got it working now. Main problem was my implementation of bindless textures, I was previously testing on non-AMD hardware.
