### ISSUE TITLE
What does AMFContext::LockOpenGL and ::UnlockOpenGL actually do?

### ISSUE THREAD

**Issue by Findus79** [GPUOpen-LibrariesAndSDKs/AMF#140]
I stumbled across the use of these calls, but what do they actually do?

**Comment by MikhailAMD** [comment]
They synchronize access to shared between app and AMF an OpenGL context guaranteeing in multi-threaded environment that AMF will call wglMakeCurrent only after acquiring the lock. And the calling code expected to do the same. There are similar locks for DX9, DX11 etc. There are also small classes to help with the locks in the same header.

**Comment by Findus79** [comment]
But when to use it? Documentation is, well, non-existant on AMDs part. I have to use Decode/Convert in separate threads and I do the conversion to a OpenGL texture in my main rendering thread. 
I initialized AMF using the applications OpenGL context. Decoding seems to work fine, but I have no idea which constructs of AMF actually use the GL context and where I need to lock it, since there is no documentation.
Examples did not help much, there are only two examples using the OpenGLLocker helper class at all, and they don't use shared resources.
Currently I lock after calling convert to AMF_MEMORY_OPENGL (just like in PlaybackHW sample) and keep it locked until my rendering has finished. But that keeps fucking up the whole renderer. If I also lock when calling decode or convert, my rendering part works, but I keep getting the following error from AMF:
`[AMFDeviceOpenGLImpl]   Error: ..\..\..\..\..\runtime\src\core\DeviceOpenGLImpl.cpp(740):Assertion failed:AMFOpenGLContextImpl::Lock() wglMakeCurrent failed 170`

a) would have been nice to output which context is trying to be made current
b) which brings me to the question: which context is it working on? when dumping OpenGL calls using apitrace I keep seeing the context I gave to AMF, but once in a while it uses a second context.
c) why are there so many wglMakeCurrent calls in the my trace file? Sometime 5 wglMakeCurrent to the same context.

**Comment by MikhailAMD** [comment]
AMF will use the context provided in InitOpenGL() and will not create another context considering everything was initialized correctly. 
AMF will use GL context in color converter if it was programmed to do so. It will also use it in interops between OpenGL and OpenCL.
Note the convert from DX1 to OpenGL will go via system memory due to the lack of interops. To avoid this you can use color converter:
1. Initialize DX11 (DeviceDX11.cpp)
2. Initialize OpenGL on the same adapter as DX11. (DeviceOpenGL.cpp)
3. Initialize OpenCL with DX11 and OpenGL device and context. (DeviceOpenCL.cpp)
4. Pass all of the devices to AMFContext: InitDX11(), InitOpenGL(), InitOpenCL()
5. Configure decoder to run on DX11
6. Configure color converter to make output as OpenGL
7.  Configure color converter to use OpenCL as engine

So OpenCL in converter due to available interops will works as a bridge between DX11 and OpenGL 

Locking: sInce OpenGL is used in converter only AMF will try to use the lock in QueryOutput of color converter. 
error code 170 is "The requested resource is in use"

AMF in Lock() call stores current OGL context and restores it in Unlock() call. From what you see in apitrace you probably have more then one context in the app.

General rule: use one context with AMF and lock while you render or present and unlock right after.

**Comment by Findus79** [comment]
Thanks for the headsup. I could fix some problem using the "Locking Rule". One question remains though: I copy the AMF texture to a OpenGL "rendertarget" (fbo) in my application. If I use this rendertarget with glBindTexture everything is ok, but if I use it as a bindless texture, the image is corrupted. This only happens with the AMF texture, all other rendertargets in the application work fine when used with bindless texturing. Do you have any idea why this would happen?

**Comment by MikhailAMD** [comment]
I can think of two things: allocation parameters or synchronization. AMF allocates OGL textures this way:
    CALL_GL(glGenTextures(1, (GLuint*)(&pSurface)));
    CALL_GL(glBindTexture(GL_TEXTURE_2D, CastPointer<GLuint>(pSurface)));
    CALL_GL(glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_BGRA_EXT, GL_UNSIGNED_BYTE, 0));
To check synchronization obviously you should try to insert glFinish().
What kind of corruption do you see?
What is the method of copy, a shader with two triangles?
When you are in doubt you can always replace AMF texture allocxation with a custom one by passing AMFDataAllocatorCB to converter and using CreateSurfaceFromOpenGLNative to warp AMFSurface around OpenGL handle.

**Comment by Findus79** [comment]
Hi,

sry for the late response, I was out of office over the weekend. I just finished implementing the callbacks to feed our own textures to AMF, and now it works :)

Thanks a lot for your help!

**Comment by MikhailAMD** [comment]
Great, you are most welcome. One question: what did you do differently in allocation?

**Comment by Findus79** [comment]
Hi,

I don't exactly know 😂 In the first iteration I took the texture from the AMF converter and rendered it on a texture allocated from my engine (like in the PlaybackHW sample in the OpenGL path, only with a Rendertarget instead of the Backbuffer). This resulted in a crippled image. Once I implemented the Callback version it worked. At first I thought it is because I am using bindless textures in my engine, and there is some syncing problem.
