### ISSUE TITLE
Null Pointer Crash (EIP = 0x0) in AMF Runtime if AMD Driver overrides GPU to iGPU

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#149]
This is an odd unsolvable case for the AMD Encoder Plugin. The DirectX11 instance is created with the proper device Id, as confirmed by the name of it. But when trying to initialize AMF on it, a crash happens.

As the device was properly identified as an AMD GPU which should be allowed to use AMF, this seems like a bug in the AMD Driver.

* Crash Log: https://obsproject.com/logs/fEORNpsT3udLxWv5
* Log: [2019-02-10 11-39-16.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/2851168/2019-02-10.11-39-16.txt)

**Comment by MikhailAMD** [comment]
This card doesn't have encoder and decoder and Capability Manager correctly reports that there is no encoder. 
https://www.techpowerup.com/gpu-specs/radeon-r5-m330.c2681
The runtime shouldn't crash though, but should report failure on component creation.  Which  call causes the crash?

**Comment by Xaymar** [comment]
I believe it to be the Init() call.

**Comment by MikhailAMD** [comment]
But CreateComponent should return NULL. Please check if that's the case.

**Comment by Xaymar** [comment]
Unfortunately I am not the one experiencing this problem, just reporting it. This is a bug exclusive to the GPU override in the AMD Driver App

**Comment by MikhailAMD** [comment]
You have to to enable AMF internal tracing. If CreateComponent fails it should be a log entry. I don't see it.

**Comment by Xaymar** [comment]
This is just going from the log file:

1. The R5 M330 was properly scanned for capability, and marked as not supporting H264 and H265. There was no error here.
2. There is a second unknown AMD GPU being listed now, which crashes when creating an encoder for it. As the debug information was corrupted by the 0xC0000005 (NullPointerCall), i don't know exactly which encoder failed to create.
3. However both encoder initialize the same way:
    1. AMF_RESULT CreateContext
        * If AMF_RESULT != AMF_OK, throw std::exception.
    2. Create D3D9 or D3D11 instance for AMF
    3. Initialize D3D9 or D3D11 with previously created instance. (AMF_RESULT InitDX(9|11))
        * If AMF_RESULT != AMF_OK, throw std::exception.
    4. If OpenCL is enabled, Initialize OpenCL (AMF_RESULT InitOpenCL)
        * If AMF_RESULT != AMF_OK, disable OpenCL
    5. AMF_RESULT CreateComponent AMFVideoConverter
        * If AMF_RESULT != AMF_OK, throw std::exception
    6. Bunch of SetProperty with AMF_RESULT checks, throw std::exception if mismatch or error.
    7. AMF_RESULT CreateComponent for the codec
        * If AMF_RESULT != AMF_OK, throw exception.
    8. SetUsage and SetProperty for the remaining codec specific parameters that are not in some way shared or configurable at runtime.

I don't actually initialize them at that point, but I do destruct them if the initialization worked:

1. If not null, Terminate on Encoder Component
2. If not null, Terminate on Converter Component
3. If not null, Terminate on Context

As none of the std::exceptions happened, I'm fairly sure that CreateComponent can't have returned NULL, as that would mean it should not have returned AMF_OK. That means that whereever this code is currently in is actually just accessing a nullptr. Unfortunately due to non static addresses, I'm not entirely sure where in the binary we actually are (but I'm trying to figure it out at the moment).

**Comment by MikhailAMD** [comment]
I don't see the second AMD GPU. The log is below. I checked the logic in the plug-in code on github, no need to repeat. Since we both are working remotely with a client we need AMF tracing enabled. 
The plug-in capability manager failed to create component and logged this appropriately so how could it be that later the plug-in succeeded to create the same component? 
Maybe PLOG_DEBUG is not enabled?
If Createcomponent fails there is a call QUICK_FORMAT_MESSAGE but this is not tracing/logging yet. So we really don't know how the code behaves. 

11:39:17.264: ---------------------------------
11:39:17.264: Initializing D3D11...
11:39:17.264: Available Video Adapters: 
11:39:17.273: 	Adapter 1: AMD Radeon (TM) R5 M330
11:39:17.273: 	  Dedicated VRAM: 2138697728
11:39:17.273: 	  Shared VRAM:    4250116096
11:39:17.273: 	  output 1: pos={0, 0}, size={1366, 768}, attached=true
11:39:17.273: 	Adapter 2: Intel(R) HD Graphics 5500
11:39:17.273: 	  Dedicated VRAM: 134217728
11:39:17.273: 	  Shared VRAM:    4250116096
11:39:17.278: Loading up D3D11 on adapter AMD Radeon (TM) R5 M330 (0)
11:39:17.309: D3D11 loaded successfully, feature level used: 45056
11:39:18.461: ---------------------------------

**Comment by Xaymar** [comment]
Unfortunately no reply from the user that experienced the crash yet. However I did figure out that the crash happens due to D3D9 initialization. Even though the Intel adapter should be the main one (display), the AMD adapter was found.

**Comment by Xaymar** [comment]
Can still reproduce this with the Direct3D 9 fallback, will likely have to figure out a way to detect if Windows or the AMD Driver is messing with adapter detection on D3D9 and then disable initialization on there.

**Comment by Xaymar** [comment]
Since this is pretty much a Direct3D9-only issue, which is only used as a fallback on Windows 7, I'll close this. The recommended way to use the plugin is Direct3D11 anyway, and people should really switch away from Windows 7 already.

**Comment by shuangshu** [comment]
I have the same problem in Win7 X64, 
 AMD Radeon RX 580 2048SP   Driver Version: 26.20.15029.27017  Runtime: 1.4.16.0 when call  EnablePerformanceMonitor or InitDX9 crash
