### ISSUE TITLE
H.264/HEVC lossless support?

### ISSUE THREAD

**Issue by SirKayten** [GPUOpen-LibrariesAndSDKs/AMF#174]
Hi there!
It might be a niche, but do AMD graphics cards support lossless H.264/HEVC encoding? Especially Navi? If so: YUV 4:2:0 only? What about 422, 444, RGB or P010?
Thanks in advance!

**Comment by MikhailAMD** [comment]
If you want lossless you can set CQP rate control mode and force I-frame or IDR-frame on every submission - should work for H264 and HEVC. 
YUV 4:2:0 only. Navi supports 10 bit (P010).

**Comment by SirKayten** [comment]
Thanks Mikhail.
Could Navi support 422, 444 and/or RGB in a future release of AMF or is this a hardware limitation?

**Comment by MikhailAMD** [comment]
HW doesn't support 422 or 444.  Older GPUs would use GFX for color conversion but Navi Encoder HW does support direct RGBA input. Check AMF_VIDEO_ENCODER_CAP_COLOR_CONVERSION in the encoder AMFCaps interface for AMF_ACCEL_HARDWARE and program the encoder to accept RGBA.

**Comment by Ciancy28** [comment]
> If you want lossless you can set CQP rate control mode and force I-frame or IDR-frame on every submission - should work for H264 and HEVC. YUV 4:2:0 only. Navi supports 10 bit (P010).

Sorry for bumping such an old issue, but i've been trying to do some lossless encoding with amf through ffmpeg with an RX 7600 unsuccesfully and this issue seems to be the only place where lossless encoding with amd amf has ever been discussed.

By setting all the quantization parameters to 0 and GOP size to 1 (I-frame for every frame) i can get extremely close to lossless, but not actually lossless.

<img width="938" height="594" alt="Image" src="https://github.com/user-attachments/assets/85d8d99d-56b1-40e3-8cec-e6d22c0d482d" />

The commands I've used are the following:
`ffmpeg -i big_buck_bunny_1080p_h264.mov -c:v hevc_amf -usage transcoding -quality quality -rc cqp -qp_i 0 -qp_p 0 -qp_b 0 -c:a copy -g 1 hevc_amf.mp4`
`ffmpeg -i big_buck_bunny_1080p_h264.mov -c:v h264_amf -usage transcoding -quality quality -rc cqp -qp_i 0 -qp_p 0 -qp_b 0 -c:a copy -g 1 h264_amf.mp4`

The source in this case is NV12 (yuv420 8 bit), but I've had the same result with 10 bit p010 content.

Perhaps there's something that i've missed?
