### ISSUE TITLE
Determine max decode density capacity

### ISSUE THREAD

**Issue by BlueBox1** [GPUOpen-LibrariesAndSDKs/AMF#202]
Hi, has anyone any ideas on when the AMF decode interface is at max performance?
pCaps->GetProperty(AMF_VIDEO_DECODER_CAP_NUM_OF_STREAMS, &supported);
Reports 16 on an E8870 for example, but you'll be lucky to get x2 1080p decodes.
What is the best way of programmatically determining this upper limit?

Can we read the GPU memory used and create a static table for known limits as a worst case?
How can we read the GPU memory with AMF?
Thanks for any pointers, may be missing something as it seems a pretty fundamental task, encoding or decoding.

**Comment by MikhailAMD** [comment]
Yes, 16 streams is the maximum supported by hardware. The actual real-time performance is very different for each GPU/APU. You may want to run a short profiling test, similar to SimpleDecoder sample to identify this and store this info attached to DeviceID (see IDXGIAdapter::GetDesc).
You can get total video memory by calling IDXGIAdapter::GetDesc,  
For dynamic memory info:  IDXGIAdapter3::QueryVideoMemoryInfo
Not sure what you meant by "read GPU memory". 
- If you want to use the result of decoding in your app as D3D11 texture you can access ID3D11Texture2D* via AMFPlane::GetNative() 
- If you want to use the result of decoding in the system memory you can use AMFData::Convert(AMF_MEMORY_HOST) or AMFData::Duplicate(AMF_MEMORY_HOST, &pHostData) and then get the real system memory pointer by AMFPlane::GetNative(). 
Please note that AMFSurface is derived from AMFData and you can use smart pointers to call QueryInterface():
AMDDataPtr pData;
decoder->QueryOutput(&pData);
if(pData != nullptr){
AMFSurfacePtr pSurface(pData);
}

**Comment by BlueBox1** [comment]
Thanks Mike, I'll use a video memory marker against a known piece of hardware for a known decode density count -  IDXGIAdapter3::QueryVideoMemoryInfo
This way we will know when to stop asking for more decode streams.
That should do the trick unless you know of a simpler way. Thanks again.

**Comment by BlueBox1** [comment]
Hi, unfortunately,  IDXGIAdapter3::QueryVideoMemoryInfo is process specific. Does anyone have any other ideas on how to determine the max decode capacity of hardware via the AMF or other API for AMD hardware? For NVIDIA we load the native nvapi and query the video memory used as a marker for various types of hardware decode density capabilities.

**Comment by BlueBox1** [comment]
Hi, does a method exist whee a user can read the number of active decode sessions for a particular device? Across process boundaries. That we I can limit the amount of decode sessions in a lookup table.
Unfortunately, we are not in a great position to count ourselves. Cheers,

**Comment by MikhailAMD** [comment]
You can only try to create a decode session and the creation will fail if the system is out of sessions.

**Comment by BlueBox1** [comment]
Thanks for the comment Mikhail, unfortunately that is no use to the user, for example, an E8870 suggests it can handle 16 concurrent streams, however, it can only decode two 1080p h264 at 30 FPS. Developers need to know when the hardware is exhausted. Perhaps the only option is to use static lookup tables and known benchmarks (very hard at different resolutions and frame rates and formats). Another way is to use a marker, reading available run-time video memory usage across process's. However, we cannot find any AMD API that allows you to do this (ADl can on Linux only). Windows DirectX is process specific. It seems a massive hole in API support, are we missing anything? GPU-z can do it (closed source) Open hardware monitor cannot (open source).

**Comment by MikhailAMD** [comment]
The number of stream limitation is derived from HW memory limitation but has nothing to do with actual real-time GPU performance. The problem with such benchmark is that if it is a static table, it would be huge and inacurate because performance depends on frequency and the frequency sometimes are set not by us but by OEM manufacturers. The dynamic monitoring would be temporal and provide only average results. But it is possible to do: one example is here:
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon
They don't provide source code as they did earlier but they use these APIs: https://docs.microsoft.com/en-ca/windows/win32/api/winevt/
https://docs.microsoft.com/en-us/windows/win32/perfctrs/performance-counters-functions
 I would probably try to write something similar. To find proper counter you may want to use:
https://docs.microsoft.com/en-us/windows/win32/perfctrs/browsing-performance-counters
BTW: I didn't try all this.
