### ISSUE TITLE
about chromatism

### ISSUE THREAD

**Issue by yanrk** [GPUOpen-LibrariesAndSDKs/AMF#210]
Hi, I got a problem about h264 encode on chromatism

the d3d11 texture format is *DXGI_FORMAT_B8G8R8A8_UNORM*
the converter output format is *AMF_SURFACE_NV12*
and the encoder type is *AMFVideoEncoderVCE_AVC*

the decoder is ffmpeg-h264
the player with SDL2

if the decoder has graphics card, and use dxva hardware acceleration (*AV_HWDEVICE_TYPE_DXVA2*), the color difference is very small, such as RGB(247, 28, 36) to RGB(246, 28, 37)

if the decoder has graphics card, and use other hardware acceleration (like *AV_HWDEVICE_TYPE_CUDA*) or no hardware acceleration, the color difference is larger, such as RGB(247, 28, 36) to RGB(219, 5, 40)

if the decoder has no graphics card, and use dxva hardware acceleration (*AV_HWDEVICE_TYPE_DXVA2*), the color difference is larger neither, such as RGB(247, 28, 36) to RGB(219, 6, 36)

I think it is not about decoder configurations because use other encoder tools like OBS, it works well on amd-h264, so must something wrong on my encode code, do you have any suggestions or ideas, thanks.

**Comment by MikhailAMD** [comment]
In short, what it looks like that after decoder you use several color converters from NV12 to RGB and they use different color standards. 

From AMF encoder perspective:
1. Since your input is RGB you have to do color conversion to NV12. Assume you are using AMF video converter. It has three main options: 
 - BT 609 (normally used for SD resolution)
 - BT 701 (normally used for HD resolution)
 - JPEG (full range BT609 - special cases )
3. The decision which option to use comes from the calling application.
4. Encoder and H264 codec format has no idea which color space was used for conversion. There is one Boolean flag in VUI header which can indicate that full range was used. You can set it for AMF encoder via AMF_VIDEO_ENCODER_FULL_RANGE_COLOR property.
5. On decoder side the decoder always produces NV12 (or similar but always 4:2:0). The data inside should be the same for all decoders.
6. After that NV12 to RGB color converter is used.
7. The calling application decides which option to use in the converter:  based on resolution, and sometimes on this flag in VUI header.  Also, it could be some explicit options. 
As you can see from the encoder side your control is limited by matching conversion standard with resolution. You can use full range only if you are sure decoder converter supports it. In this case you can use the encoder flag to pass the information. 
From the values you show it seems that you enabled full range converter option on encoder side but did not for some cases on the decoder side: 247 is from wide range(0-255) but 219 is a clipped value from normal range (16-219).
See this for some details: https://en.wikipedia.org/wiki/YCbCr

**Comment by yanrk** [comment]
@MikhailAMD the 'color_full_range' is default to false, and 'color_profile' is default to -1, if the decode machine use graphics card to acceleration, need set 'color_profile' to 'BT-709',  if not, need set 'color_profile' to 'BT-601', then the color difference are all small, it is the result of the test. thank you very much!
