### ISSUE TITLE
Where is DEM (Direct encode mode)?

### ISSUE THREAD

**Issue by dvv47** [GPUOpen-LibrariesAndSDKs/AMF#24]
With AMD Media SDK 1.1 was samples to Direct encode mode that allow encode video card buffer without passing directx or opengl frames.
In new sdk i just found few constant about DEM and no more

**Comment by MikhailAMD** [comment]
DEM feature is retired. The capture and direct submission to encoder is more effective.

**Comment by Xaymar** [comment]
So there is no alternatives to NvIFR and NvFBC now? NvFBC previously had DEM on AMD cards, while NvIFR is still an Nvidia only feature.

**Comment by dvv47** [comment]
Looks like self coded capture and direct encode feature cover all features of NvIFR.
But how to make framebuffer encode I can't understand

**Comment by M4RK22** [comment]
@MikhailAMD Ok, you dropped DEM feature, but would be good to have a framebuffer/render target capture at driver level (low performance hit) that allows to capture directly instead of DX/OGL frame copy. And following the open license of AMF can be implemented in OBS and other applications.

**Comment by MikhailAMD** [comment]
We are considering this feature. Meanwhile the best performance improvement OBS project may have is to avoid copy of the captured frame to system memory and transferring it back to video memory for encoding. For that app should share DX device (or create compatible device object and use textures /surfaces with shared handles).

**Comment by dvv47** [comment]
@MikhailAMD For me main purpose of NvFBC or DEM is low latency encoding without using self development capture plugins.
Because it is really hard to maintain a lot of different games and game engines, and find correct entry point for render target :)

**Comment by MikhailAMD** [comment]
I hear your request for easy capture API.
I know that OBS has multiple capture techniques implemented but there is no single bullet.

**Comment by Xaymar** [comment]
DXGI offers a display duplication mode, which can be used to replace DEM with next to no extra impact. Game DVR seems to use this for fullscreen DX11 games.

**Comment by MikhailAMD** [comment]
Conclusion: there is no DEM in AMF,

**Comment by nathankidd** [comment]
I'd encourage AMD PMs to consider a capture-to-D3D/OpenGL feature.   NVIDIA's DEM counterpart, NVFBC, has gone through the same kind of transition, deprecating direct capture->encode, but rather than drop capture entirely, it provides a D3D Surface to the entire framebuffer content.  This is very useful for remote desktop type applications that can't assume a full-screen OpenGL/D3D game with a single buffer to capture.   It also allows such applications to decide if video encoding even makes sense.  Not all desktop content likes lossy compression. Microsoft's Desktop Duplication API doesn't work on Windows 7, so there's still value in a separate capture API. (Win 7 EOL is 3 years away.)   Bonus API features: hardware frame differencing regions, Linux support.

**Comment by nathankidd** [comment]
For FirePro users https://github.com/GPUOpen-LibrariesAndSDKs/DOPP is related.
