### ISSUE TITLE
Performance numbers of AV1 HW decoding capability for RDNA2 cards

### ISSUE THREAD

**Issue by NikosDi** [GPUOpen-LibrariesAndSDKs/AMF#241]
Haven't seen anywhere performance numbers of AV1 HW decoding capability for RDNA2 cards.

Is it enabled in drivers ?

Do you have any performance numbers to provide ?

**Comment by MikhailAMD** [comment]
Yes, with the latest SDK release and latest drivers AV1 decoding is enabled. It is supported in Navi21 (RX 6xxx series). Performance should be similar to other codecs. I cannot provide exact numbers because exact measurements depend on many factors: characteristics of the stream, active power management policy etc.

**Comment by NikosDi** [comment]
For example, can RX 6000 cards play a YouTube 8K60fps HDR AV1 clip without dropping frames ?

What is the Video Processor decoding usage during playback of such clip ?

If you have an HDR display, just turn HDR on and select 4320p60 stream even without having 8K display for this clip with any compatible browser:
https://www.youtube.com/watch?v=Yds5jgqmYpE

**Comment by NikosDi** [comment]
I managed to find some reviews reporting that both Intel's AV1 decoder of Tigerlake and AMD's RDNA2 AV1 decoder of RX 6000 series cards can decode YouTube AV1 videos up to 8K30 fps

Only nVidia's Ampere RTX 3000 series can decode AV1 at 8K60 fps

When availability and price become reasonable, I intend to buy this kind of hardware and do some benchmarks on my own.

You may close this ticket.
