### ISSUE TITLE
Radeon Software 21.4.1+ AVC/HEVC Failed to start recording

### ISSUE THREAD

**Issue by Lithium64** [GPUOpen-LibrariesAndSDKs/AMF#264]
Since it seems to be a driver issue, because i can't record with relive either. I'm reposting this issue here, since driver 21.4.1 AMF and relive are broken on windows.

https://github.com/obsproject/obs-studio/issues/4689

**Comment by MikhailAMD** [comment]
According to the link the problem was resolved. Can we close the issue?

**Comment by Poilaucul** [comment]
Was AMF support dropped past Radeon Software 21.3.2 ?

**Comment by MikhailAMD** [comment]
AMF is active and supported in all drivers.

**Comment by Poilaucul** [comment]
Glad to hear that, however past Radeon Software 21.3.2 AMF doesn't work still in OBS, yesterday I had to downgrade from Radeon Software 22.5.1 to Radeon Software 21.3.2 to have AMF working again, it's been two years now since Radeon Software 21.3.2 and we seen no serious focus on this issue or outlook of serious improvement of AMF.

**Comment by MikhailAMD** [comment]
The failing OBS log would be helpful. The OBS ticket above was closed.
AMF is used in many applications, we monitor for errors. Did you check obs-amf branch in OBS with new OBS-AMF integration?
