### ISSUE TITLE
Undocumented options

### ISSUE THREAD

**Issue by e00E** [GPUOpen-LibrariesAndSDKs/AMF#303]
The recent releases mention

- New encoder usage presets
- Support for consecutive B-frames and adaptive miniGOP for AVC Encoder

I can see that these show up in the EncoderVCE and EncoderHEVC headers but they do not show up in the PDF documentation for these components. There are probably other options that are also missing from the pdf. It would be useful if someone went through these headers and made sure all the options show up in the pdf including the default values for the various presets.

**Comment by cs9kc** [comment]
Giving this a bump as the documentation is indeed out of date.

I dug through the code and can't find any information on Adaptive MiniGOP.  Could we get a quick description and ideal use-case (if any) for Adaptive MiniGOP, as well as if there are any special considerations that need to be put into the code while asking for Adaptive MiniGOP, similar to this post, https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/318#issuecomment-1142111074, @rhutsAMD?

Thank you!

**Comment by MikhailAMD** [comment]
The AMF_VIDEO_ENCODER_ADAPTIVE_MINIGOP parameter is documented in AMF_Video_Encode_API with the following description: bool; default = false; Disable/Enable Adaptive MiniGOP, can enable with PA enabled.
More info: It currently only takes effect when PA is enabled. The video content is pre-analyzed to determine the miniGOP adaptively. The number of consecutive B frames in any miniGOP is restricted by AMF_VIDEO_ENCODER_MAX_CONSECUTIVE_BPICTURES.
An example command line based on TranscodeHW.exe is like:
_TranscodeHW.exe -input inputfile -output outputfile -width 1920 -height 1080 -usage transcoding -qualitypreset speed -Profile 100 -ProfileLevel 5.2 -RateControlMethod vbr -TargetBitrate 16000000 -DeBlockingFilter true -FRAMES 963 -IDRPeriod 256 -FrameRate 60,1 -Codec h264 -engine dx11 - EnablePreAnalysis true -PAEngineType host -MaxConsecutiveBPictures 3 -AdaptiveMiniGOP true - PeakBitrate 20000000 -VBVBufferSize 16000000_

**Comment by cs9kc** [comment]
Thank you so much for your response.  I'm putting together some documentation for use with OBS Studio's newly-rewritten AMD Texture-Based encoder that addresses AMF directly, instead of going through ffmpeg.  I've been trying to wrap my head around all of the available features, but...

> parameter is documented in AMF_Video_Encode_API

Unless newer documentation is kept somewhere that I have missed, then [AMF_Video_Encode_API.pdf](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_API.pdf) does not contain MiniGOP.  I've had to look at notes left in AMF's code to gather a lot of the information that I currently have about some of the more obscure/less used features.

I also find the descriptions and use-cases of some other features lacking, but I'll open new issue tickets for those as I come across them.  Thanks again, and thanks in advance for your help!

If newer documentation

**Comment by MikhailAMD** [comment]
The description does exist in the newer version of the document. We will push update soon.  Thanks

**Comment by rhutsAMD** [comment]
Hi @cs9kc, just confirming whether you have found the updated documentation for `AMF_VIDEO_ENCODER_ADAPTIVE_MINIGOP` and  `AMF_VIDEO_ENCODER_MAX_CONSECUTIVE_BPICTURES` included inside the last AMF release v.1.4.26?

**Comment by cs9kc** [comment]
Hello @rhutsAMD!  Thank you for the ping.  I did indeed see the updated descriptions for Adaptive MiniGOP and Max Consecutive BPictures!  Thank you all for updating those entries! <3
