### ISSUE TITLE
RX 6650 XT encoder capability vs higher end models

### ISSUE THREAD

**Issue by Johl7** [GPUOpen-LibrariesAndSDKs/AMF#439]
Hello, i would like to know if the 6650 XT posesses the same encoding capabilities as a 6900 XT, using these params 'HighMotionQualityBoostEnable=true EnablePreAnalysis=true RateControlPreanalysisEnable=true PAHighMotionQualityBoostMode=0 PATemporalAQMode=2 PAFrameSadEnable=true AdaptiveMiniGOP=false PALookAheadBufferDepth=41 PACAQStrength=2' in OBS i get encoder overloads when streaming/recoding a game, while someone with a 6900 XT seems to be able to use em with ease, other settings are CBR, Qual Pset, 2 kframe int, High Profile and 3 MaxBfs.

**Comment by rhutsAMD** [comment]
The RX 6900 XT is notably more powerful than the RX 6650 XT so it is expected to be able to use higher encoding and PreAnalysis settings with the more powerful RX 6900 XT.

**Comment by Johl7** [comment]
Yes, i know that the 6900 XT is miles ahead when it comes to performance, but given a scenario where both have room to spare(usage and vram usage) shouldnt both have equal encoding performances?

**Comment by DimkaTsv** [comment]
> Yes, i know that the 6900 XT is miles ahead when it comes to performance, but given a scenario where both have room to spare(usage and vram usage) shouldnt both have equal encoding performances?

No, because physical size of encoder block on die is different between 6650XT and 6900XT. It is done to save on silicon for main GPU job - image rendering.
So there is physical limit to both encoder and decoder performance (for example RDNA2 decoder limit is 8k30 FPS. Technically slighly higher, but not enough for 8k60).

**Comment by Johl7** [comment]
Ohh, yes... TAQ 1 seems harder to get enc overloads with, but it hits ingame performance quite a bit(at least 10%). TAQ setup i will prob leave at 2 and setting preset to Bal if needed. Thanks

**Comment by MattyFresh68** [comment]
> > Yes, i know that the 6900 XT is miles ahead when it comes to performance, but given a scenario where both have room to spare(usage and vram usage) shouldnt both have equal encoding performances?
> 
> No, because physical size of encoder block on die is different between 6650XT and 6900XT. It is done to save on silicon for main GPU job - image rendering. As you cannot harm decoder performance, usually only encoder block is getting cut down. Most often there is split between low and mid tier vs high tier models, where encoder block is halved for lower tier models in comparsion. So there is physical limit to both encoder and decoder performance (for example RDNA2 decoder limit is 8k30 FPS. Technically slighly higher, but not enough for 8k60).
> 
> Using PreAnalysis is fine, and amount of lookahead frames doesn't impact performance that much. But i would definitely recommend you to switch PATemporalAQMode=2 to 1. TAQ being set up to 2 is most penalizing parameter on my experience, and difference between 1 and 2 is often quite controversial even at transcoding. 2 will compress data stream noticeably more, but will also inflict slightly higher quality penalty.

Do you have specific verified sources on the physical difference between the various cards? Not saying that's not accurate, but am now genuinely curious

**Comment by MattyFresh68** [comment]
"Should be" isn't very scientific haha. Nvidia does indeed handle things differently so it's not really fair to say "amd does it this way too". 
Would need actual physical data to support the encoder setup being different from 6650 to 6900.

**Comment by DimkaTsv** [comment]
"Would need actual physical data to support the encoder setup being different from 6650 to 6900."

Would definitely be nice to have. But not many people own variety of card from low to high tier and ready to do such benchmarking, i guess (as i literally cannot find any info. Frankly speaking i cannot even find encoder performance benchmark for low tier Nvidia cards).
But i would not be so naive to think that AMD won't use same cost cutting and upsell measure as Nvidia does (cost cutting as it   allows to save worse silicon sample by cutting part of VCN block) (and upsell one as it forces people that use video editing to turn towards high-end GPU instead of low-end). Moreover, using more silicon real estate for encoder block on low-tier card would be quite a money waster from AMD side, because not every user requires additional performance on encoder, especially among people that play on low tier GPU's 

Moreover, as additional argument Navi 24 (aka 6500 and 6400 GPU) don't have VCN encoder blocks at all (and mobile 6500 6400 also lack VCN AV1 decoder in addition to that). 
But, blocks aren't fractional, so there should be some die size range where 1 becomes 2 if you understand what i mean. (7800XT have larger encoder than 7700XT iirc). Such is silicon architecture, you cannot fractionalize parts.

**Comment by DimkaTsv** [comment]
> (though this is a very limited sample size and would like to see more test subjects haha)


Well, i can help you all with that. Use ffmpeg or vceencc, take same exact source file, and use same exact benchmarking or transcoding command to initiate process. 
You will both get average FPS rendered metric, and compare values. They should be noticeably different from each other.

**Comment by rhutsAMD** [comment]
It is possible that the encoding difference your are seeing is a side effect of the large increase in GFX performance in the RX 6900 XT over the RX 6650 XT. The GFX queue is the HW 3D graphical queue used by D3D11 for compute as well as by the game for rendering.

You have enabled PA which runs on the GFX queue and interferes with the game during recording. You may try the other PA engine types as an experiment. The Host version of PA has received some performance optimizations recently and would not run on the GFX queue. Host means the use of the CPU, while on the other hand, DX12, OpenCL, and Vulkan will use the HW compute queue. In any case, there will be less interference with games than the default DX11.

`PAEngineType=4`

-	Host(1)
-	DX11(3)
-	OpenCL(4)
-	Vulkan(10)
-	DX12(11)

**Comment by azamet90** [comment]
i have rx6900xt and also encoding problems with EnablePreAnalysis

**Comment by Johl7** [comment]
> It is possible that the encoding difference your are seeing is a side effect of the large increase in GFX performance in the RX 6900 XT over the RX 6650 XT. The GFX queue is the HW 3D graphical queue used by D3D11 for compute as well as by the game for rendering.
> 
> You have enabled PA which runs on the GFX queue and interferes with the game during recording. You may try the other PA engine types as an experiment. The Host version of PA has received some performance optimizations recently and would not run on the GFX queue. Host means the use of the CPU, while on the other hand, DX12, OpenCL, and Vulkan will use the HW compute queue. In any case, there will be less interference with games than the default DX11.

Try running with either OpenCL or Host, were the ones that performed the best in  here
