### ISSUE TITLE
[Question]: Will Adrenalin 22.6.1 be supported?

### ISSUE THREAD

**Issue by NorthTen** [GPUOpen-LibrariesAndSDKs/AMF#440]
I've got a new R5 340X, got some information about it online, says it supports VCE 1.0, so it should be able to work with VCE.
Although, using sunshine, there's an error. 

`Error:[hevc_amf @ 00000220af4de780] CreateComponent(AMFVideoEncoderHW_HEVC) failed with error 10`

**This isn't accurate as I was not logged into github on the virtual machine, so I had to search up that error code and grab it from someone else who also got that error code in particular.**

Instead of HEVC, in my case I intend to utilize h264, and the h264 encoder was giving out that error code (`10`).
So now it relied on software rendering which I mind you introduces some short-term lag with some background tasks going on, and possibly on some CPU intensive games it could introduce more lag.

So from my findings, I can assume that, that error code means that the intended encoder isn't available on the system (where the drivers reside), and probably not on my GPU.

The driver being used in question is `22.6.1` (Adrenalin Edition).
I could try to change the driver version.

OS version is Windows 10, by the way.

**Comment by DimkaTsv** [comment]
Can you generate proper error log please?
AMF is unable to "support" or "not support" driver version, because AMF runtime already exists within drivers since Media SDK was transformed into AMD. Only difference is AMF runtime version, but it should be backwards compatible up to:
* Version 1.3: AMD Radeon Software Crimson Edition 16.7.3 (16.30.2311) or newer . Which your driver version is definitely fits to. 

You can also try and test if AMF runtime in driver works properly for such old GPU via AMF API caller like like VCEEncC. 

For example simple command of: [to use create .bat file in folder where VCEEncC executable will be placed, fill it with code below, save, then drag and drop some video on top of it]
```
 %~dp0\VCEEncC64.exe -i %1 -o "%~n1_processed%~x1" --codec h264 --log vceencc_log.txt --log-level info
pause
```
That command should take dragged video as input, use h264 as specified output codec (not that you can do something else here), use default parameters and output result with processing log being piped into "vceencc_log.txt".

 
Also, what version of sunshine had you used? There was this issue reported, which can be related to your problem? 
https://github.com/LizardByte/Sunshine/issues/1559

**Comment by rhutsAMD** [comment]
The R5 340X (Oland) does not have an encoder. [Video Coding Engine - Wikipedia](https://en.wikipedia.org/wiki/Video_Coding_Engine): “Since 2012 it was integrated into all of their [GPUs](https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units) and [APUs](https://en.wikipedia.org/wiki/List_of_AMD_accelerated_processing_units) **except Oland**.”

Since your R5 340X (Oland) does not have an encoder, an `AMF_RESULT` error with value of 10 (`AMF_NOT_SUPPORTED`) is expected when attempting to create the encoder component.

**Comment by DimkaTsv** [comment]
> The R5 340X (Oland) does not have an encoder. [Video Coding Engine - Wikipedia](https://en.wikipedia.org/wiki/Video_Coding_Engine): “Since 2012 it was integrated into all of their [GPUs](https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units) and [APUs](https://en.wikipedia.org/wiki/List_of_AMD_accelerated_processing_units) **except Oland**.”

Hmm... Interesting, then TechPowerUp have errors for these GPU's, i assume? Because they mention R5 340X as:
```
Generation: Sea Islands
Mobile Variant: Mars / Opal / Litho
Graphics/Compute: GFX6 (gfx601)
Display Core Engine: 6.4
Unified Video Decoder: 4.0
Video Compression Engine: 1.0
CLRX: GCN 1.0

```
And Video Compression Engine 1.0 persists here. 

Sunshine also links to "OBS AMF support list" where under VCE 1.0 list there is no R5 340X (which is ooof for topic starter), but R5 340 and R7 340 listed instead, which is... Also called Oland? They are all tied to "Pirate Islands" generation of "Sea Islands"... 
Good lord, what the heck was happening with naming schemes back then?

**Comment by rhutsAMD** [comment]
There are several GPUs correctly named Oland which do not have VCE support ([Radeon 300 series - Wikipedia](https://en.wikipedia.org/wiki/Radeon_300_series)):
-	R5 330 (Oland Pro)
-	R5 340 (Oland XT)
-	R7 340 (Oland XT)
-	R5 340X (Oland XT)
-	R7 350 (Oland XT)
-	R7 350X (Oland XT)

The TechPowerUp page for the R5 340X and "OBS AMF support list" incorrectly mention Oland as supporting VCE.

**Comment by NorthTen** [comment]
Well, I am new to buying an AMD product, was searching for GPUs that at least had VCE 1.0, but also relatively cheap.

Turns out it doesn't. Thanks for the information, anyways.

-------- Original Message --------

**Comment by NorthTen** [comment]
R5 340X doesn't have VCE support, apparently.
