### ISSUE TITLE
[Request]: Provide AMF the capability to capture not only GPU-rendered frames, but also GPU-generated frames

### ISSUE THREAD

**Issue by SaltyBet** [GPUOpen-LibrariesAndSDKs/AMF#484]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**
- GPU-based frame generation has arrived, in many forms:
  - Up to 1 frame generated between 2 real frames:
    - API-Based:
      - [DLLS 3 Frame Generation](https://www.nvidia.com/en-us/geforce/news/dlss3-ai-powered-neural-graphics-innovations/)
      - [FSR 3 Frame Generation](https://community.amd.com/t5/gaming/amd-fsr-3-now-available/ba-p/634265)
    - Driver-Based:
      - [AMD Fluid Motion Frames (AFMF)](https://www.amd.com/en/products/software/adrenalin/afmf.html)
  - Up to 2 frames generated between 2 real frames:  
      - Capture-Based:
        - Lossless Scaling Frame Generation (LSFG):
          - [Introducing Frame Generation - LSFG](https://store.steampowered.com/news/app/993090/view/3874849112275096626)
          - [New frame capture API](https://store.steampowered.com/news/app/993090/view/4016716939420303175)
          - [LSFG 1.1 – New UI detection model](https://store.steampowered.com/news/app/993090/view/4152953363973737097)
          - [Introducing LSFG 2.0](https://store.steampowered.com/news/app/993090/view/4175477072244825321)
          - [X3 Frame Generation](https://store.steampowered.com/news/app/993090/view/4145080305033108761)
- Currently, AMF seem to allow capture of normally-rendered frames only.
- This is a request for AMD engineers to provide AMF the capability to capture not only GPU-rendered frames, but also GPU-generated frames, for all AMD-compatible methods of frame generation (FSR 3, AFMF, LSFG).

**Describe alternatives you've considered**

N/A

**Additional context**

See above.

**Comment by MikhailAMD** [comment]
By design, AMF Direct Capture supposed to capture any **presented** frame. It doesn't matter how the frame was rendered; by DWM, a full screen app, interpolation inside a game like FSR or interpolation by driver (AFMF). If I correctly understand how LSFG captures frames and presents, it should be compatible with AMF Direct Capture as well.  
AMF Direct Capture returns **visible** frame.
If your solution wants to capture every presented frame, you can use AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT but in this mode capture framerate is driven by present to the screen (flip) after any possible interpolation. If you want constant capture framerate, use AMF_DISPLAYCAPTURE_MODE_KEEP_FRAMERATE. It will return the latest visible frame at given framerate, similarly, after any possible interpolation. 
If something doesn't work, please report with ZIPped short GPUVIEW log (5-10 sec) and AMF log,
Note, that your solution should be fast enough to be able to process every presented frame.

**Comment by SaltyBet** [comment]
Thanks for replying. Good to know. Just a quick question.

Per [the current documentation](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/bc64bf6e8bfca3083755b7cbec3c23d5546fb04a/amf/doc/AMF_Display_Capture_API.md), the AMF Display Capture API requires root or super user privileges when running on Linux systems.

Is that requirement going to be relaxed eventually?

**Comment by MikhailAMD** [comment]
At this point root is required. It could be possible to avoid this in the future but with Wayland only. We will provide an update when this option is available.

**Comment by SaltyBet** [comment]
Thanks for the info.

I'll close this issue.

Cheers.

**Comment by radugrecu97** [comment]
> By design, AMF Direct Capture supposed to capture any **presented** frame. It doesn't matter how the frame was rendered; by DWM, a full screen app, interpolation inside a game like FSR or interpolation by driver (AFMF). If I correctly understand how LSFG captures frames and presents, it should be compatible with AMF Direct Capture as well. AMF Direct Capture returns **visible** frame. If your solution wants to capture every presented frame, you can use AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT but in this mode capture framerate is driven by present to the screen (flip) after any possible interpolation. If you want constant capture framerate, use AMF_DISPLAYCAPTURE_MODE_KEEP_FRAMERATE. It will return the latest visible frame at given framerate, similarly, after any possible interpolation. If something doesn't work, please report with ZIPped short GPUVIEW log (5-10 sec) and AMF log, Note, that your solution should be fast enough to be able to process every presented frame.

I've been trying to get AMF integrated into the latest Sunshine using https://github.com/LizardByte/Sunshine/compare/master...cgutman:LB_Sunshine:amd_directcapture so Fluid motion frames (AFMF) can be captured.

It almost works perfectly... But in AMF_DISPLAYCAPTURE_MODE_KEEP_FRAMERATE and AMF_DISPLAYCAPTURE_MODE_GET_CURRENT_SURFACE modes, there are regular intervals where the frames are captured out of order so it's as if I'm seeing double or a ghosted image and AMD overlay seems to be flashing on and off. Then it reverts to perfect smoothness. And back and forth.

In my setup, I was testing Red Dead Redemption 2 with AFMF. I was in fullscreen and capped the framrate with Riva Tuner Statistic Server (RTSS) to 60 fps. I specifically used RTSS because I noticed much less ghosting than when using vsync/half-rate vsync and Radeon Chill with both sliders set to 60. I have a 7800x3D CPU and 7900 XT GPU.

Now, I verified my findings with the DVR sample (I modified framerate parameter to 120) - ghosting and flashing AMD overlay.
I played back the footage frame-by-frame in VLC. Some of the frames were completely out order! 

Then I think I found the solution, I set the Display Capture mode parameter in DVR sample to AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT and voila! Perfectly smooth! There was no ghosting and no overlay flashing in the playback.

**The only problem is, that if I use it in the Sunshine implementation, QueryOutput command fails.** Does **AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT** need some special setup?

**Comment by radugrecu97** [comment]
I'll add that Sunshine relies on amfrt64.dll.

Is DisplayCapture not supported in the same way in the run-time?

**Comment by MikhailAMD** [comment]
For failure in Sunshine, please enable detailed AMF logging and provide the log here.

Regarding capturing AFMF output: PRESENT mode will return from QueryOutput at exact present/flip event from full-screen  game/app or DWM or internal present event from AFMF. FRAMERATE mode captures current visible frame. It is designed to have smooth framerate regardless of game framerate but can be out of sync with AFMF. 

Another option: instead of using AFMF from Radeon software, Sunshine and similar apps can use AMF FRC component that will do the same job as AFMF.  It can be inserted between DirectCapture and AMF encoder.

Not sure I understand the question about amfrt64.dll: This DLL is always installed into System32 folder and is the front/stub for AMF runtime. All AMF functionality works via this DLL including DisplayCapture.

**Comment by MikhailAMD** [comment]
In the latest public driver FRC supports DX11 natively.

For tracing to be sure:
debug output:
traceAMF->EnableWriter(AMF_TRACE_WRITER_DEBUG_OUTPUT, true);
traceAMF->SetWriterLevel(AMF_TRACE_WRITER_DEBUG_OUTPUT, AMF_TRACE_DEBUG);
File output:
traceAMF->EnableWriter(AMF_TRACE_WRITER_FILE, true);
traceAMF->SetWriterLevel(AMF_TRACE_WRITER_FILE, AMF_TRACE_DEBUG);
traceAMF->SetPath(L"c:\\log\\");

**Comment by radugrecu97** [comment]
> In the latest public driver FRC supports DX11 natively.
> 
> For tracing to be sure: debug output: traceAMF->EnableWriter(AMF_TRACE_WRITER_DEBUG_OUTPUT, true); traceAMF->SetWriterLevel(AMF_TRACE_WRITER_DEBUG_OUTPUT, AMF_TRACE_DEBUG); File output: traceAMF->EnableWriter(AMF_TRACE_WRITER_FILE, true); traceAMF->SetWriterLevel(AMF_TRACE_WRITER_FILE, AMF_TRACE_DEBUG); traceAMF->SetPath(L"c:\log\");

Here's the error.

```
2024-08-22 18:12:11.013     13F0 [AMFScreenCaptureImpl]   Debug: AMFScreenCaptureImpl::Init()
2024-08-22 18:12:11.013     13F0 [AMFScreenCaptureImpl]   Debug: AMFScreenCaptureImpl::Terminate()
2024-08-22 18:12:11.013     13F0 [AMFScreenCaptureEngineImplDX]    Info: ReloadTextures() new format=DXGI_FORMAT_B8G8R8A8_UNORM(87) (1920x1080) monitor=0 m_ScreenID=0 FrameCount = 0
2024-08-22 18:12:11.013     13F0 [AMFScreenCaptureEngineImplDX11]   Error: c:\constructicon\builds\gfx\six\24.20\drivers\amf\stable\runtime\src\components\ScreenCapture\DX11\ScreenCaptureEngineDX11.cpp(684):COM failed, HR = 0x80004001:SetDccSupport(disable) failed
```

Good to know about the latest release. It made me realize that sunshine isn't using the latest headers so I'm in the process of getting the new ones.

**Comment by MikhailAMD** [comment]
The last error trace is ignored in AMF. It is present in DVR sample and it works. There are no traces after?
Try to disable asserts: 
amf::AMFDebug* debugAMF;
amf_factory->GetDebug(&debugAMF);
debugAMF->AssertsEnable(false);

**Comment by radugrecu97** [comment]
Ah, I managed to figure it out. Turned out that when using AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT, the initial calls to QueryOutput return failure, and the error was handled by reinitializing the whole component, causing a constant failure loop.

Now, in the DVR sample, QueryOutput never returned failure on first try in the same mode. I'm not sure what's being done differently and if it can impact something else in the backend...

Anyway, I now have a pretty smooth experience with AFMF being captured and will experiment further to figure out the occasional minor frame drops on the stream, although there's no error on QueryOutput and I'm running the desired framerate with the planty of performance overhead. Perhaps integrating Smart Access Video to ffmpeg would do something.

**Comment by radugrecu97** [comment]
I'll get the logs for the other issues - out of order frames in the 2 modes and upload a video sample as well.

I also briefly tried the FRC component but was getting error 4 during init. I can get logs later today. I'm on the latest AFMF 2 Preview driver.

```
    // Create the FRC component
    amf::AMFComponentPtr frcComp;
    result = amf_factory->CreateComponent(context, AMFFRC, &(frcComp));
    if (result != AMF_OK) {
      BOOST_LOG(error) << "CreateComponent(AMFFRC) failed: "sv << result;
      return -1;
    }

    frcComp->SetProperty(AMF_FRC_ENGINE_TYPE, FRC_ENGINE_DX11);
    frcComp->SetProperty(AMF_FRC_MODE, FRC_ON);
    frcComp->SetProperty(AMF_FRC_INDICATOR, true);
    frcComp->SetProperty(AMF_FRC_PROFILE, FRC_PROFILE_HIGH);
    frcComp->SetProperty(AMF_FRC_MV_SEARCH_MODE, FRC_MV_SEARCH_NATIVE);

    // Initialize capture
    result = frcComp->Init(amf::AMF_SURFACE_P010, 0, 0);
    if (result != AMF_OK) {
      BOOST_LOG(error) << "FRCComp::Init() failed: "sv << result;
      return -1;
    }
```

**Comment by MikhailAMD** [comment]
FRC is working with 8-bit surfaces only. P010 is not supported.

AMF DirectCapture does not include cursor. The assumption is that it can be captured using Win32 APIs and streamed separately. If you see cursor in the captured frame, it is a bug in the driver or very unusual display setup where cursor is not HW.

**Comment by radugrecu97** [comment]
> FRC is working with 8-bit surfaces only. P010 is not supported.
> 
> AMF DirectCapture does not include cursor. The assumption is that it can be captured using Win32 APIs and streamed separately. If you see cursor in the captured frame, it is a bug in the driver or very unusual display setup where cursor is not HW.

Ah, shame about 8-bit. I'm a bit confused about the Video Convertor can it do DisplayCapture HDR to HDR encoding?

Sunshine does have a some cursor overlay component. I'll look into why it only works on certain sizes.

**Comment by MikhailAMD** [comment]
Converter can do all sorts of conversions, HDR to SDR and opposite but the best thing is that you can submit captured RGBA surface directly to encoder bypassing conversion. It supports HDR and SDR RGBA: RGBA8, BGRA8, RGBA_F16, R10G10B10A2.

**Comment by cgutman** [comment]
> Sunshine does have a some cursor overlay component. I'll look into why it only works on certain sizes.

Sunshine display capture implementations are expected to be able to provide frames that (optionally) have the cursor included. For WGC capture, that is done by simply asking the OS to include the cursor in the captured frames. For DXGI DDA capture, that requires rendering the hardware cursor image into the frames ourselves. An AMF DirectCapture implementation would require something like DDA does where it renders the cursor into the frame before handing it off for encoding.

For cases with unusual cursor sizes, you are seeing the cursor probably because it falls outside the size limits for hardware cursor rendering. You will also see the cursor when dragging windows around since Windows switches to software cursor rendering for that case to keep the cursor drawing in sync with the window being moved.

**Comment by ns6089** [comment]
> AMF DirectCapture does not include cursor. The assumption is that it can be captured using Win32 APIs and streamed separately.

@MikhailAMD But doesn't this make perfect cursor-to-frame synchronization for screen *recording* software basically unattainable? Capture backend is the exclusive holder of this synchronization data, if you don't expose it then it gets lost.

**Comment by MikhailAMD** [comment]
This is a question of performance and interaction with game on GPU. Modern displays engines handle cursor bitmap in a separate plane and any effort to merge it into captured frame requires GPU processing. Note, that you cannot draw cursor on the captured frame if the frame represents visible screen like in AMF DirectCapture so one would be forced to make a surface copy. DD API makes copy anyway. In any case, the copy and blit of cursor would be made by GPU job, by OS or by streaming app and it will interfere with game. So passing cursor bitmap separately is more efficient. Saying that, sometimes it is convenient to embed cursor into captured frame. We are debating if we should introduce such feature in DirectCapture.

**Comment by radugrecu97** [comment]
> Converter can do all sorts of conversions, HDR to SDR and opposite but the best thing is that you can submit captured RGBA surface directly to encoder bypassing conversion. It supports HDR and SDR RGBA: RGBA8, BGRA8, RGBA_F16, R10G10B10A2.

Does DisplayCapture

**Comment by radugrecu97** [comment]
> Converter can do all sorts of conversions, HDR to SDR and opposite but the best thing is that you can submit captured RGBA surface directly to encoder bypassing conversion. It supports HDR and SDR RGBA: RGBA8, BGRA8, RGBA_F16, R10G10B10A2.

I'm having several issues trying to integrate this with Sunshine. There's way too many mismatched pixel formats between FFmpeg, AMF and Sunshine.

In SDR, DisplayCapture says my monitor is AMF_SURFACE_BGRA.

Sunshine utilizes AVFrames, and [amfencode.c](https://github.com/FFmpeg/FFmpeg/blob/b730defd52ad96dbdd6ac49a6f18f3c4c5f17008/libavcodec/amfenc.c#L75) in FFnoeg maps it to { AV_PIX_FMT_BGR0,       AMF_SURFACE_BGRA }.

Problem is, [hwcontext_d3d11va.c](https://github.com/FFmpeg/FFmpeg/blob/release/7.0/libavutil/hwcontext_d3d11va.c#L93) doesn't support AV_PIX_FMT_BGR0, only AV_PIX_FMT_BGRA. So I'm in a deadlock at the moment.

So, I'll probably try some patches like [this](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240715092945.521-1-Primeadvice@gmail.com/) next.

**Comment by MikhailAMD** [comment]
You can add AV_PIX_FMT_BGRA to AMF_SURFACE_BGRA mapping. Under the hood it is the same DXGI format.

**Comment by radugrecu97** [comment]
> Converter can do all sorts of conversions, HDR to SDR and opposite but the best thing is that you can submit captured RGBA surface directly to encoder bypassing conversion. It supports HDR and SDR RGBA: RGBA8, BGRA8, RGBA_F16, R10G10B10A2.

But Sunshine uses specific pixel formats -> NV12 and P010.
I don't see how I can go without the Video Convertor.

**Comment by MikhailAMD** [comment]
> > Converter can do all sorts of conversions, HDR to SDR and opposite but the best thing is that you can submit captured RGBA surface directly to encoder bypassing conversion. It supports HDR and SDR RGBA: RGBA8, BGRA8, RGBA_F16, R10G10B10A2.
> 
> But Sunshine uses specific pixel formats -> NV12 and P010. I don't see how I can go without the Video Convertor.

That's the point: to get advantage of this feature one would need to change pipeline removing color converter. We may need to update DVR sample showcasing this but you can check EncoderLatency sample: it has an option to generate or read RGBA surfaces and submit to encoder directly without color converter as long as scaling is not needed. One can do the same with captured surfaces: AMF capture or DD.

**Comment by radugrecu97** [comment]
Hello Mikhail,

I tried integrating the FRC component now that it supports HDR but I'm having trouble with interpolation.

I have a 120 hz monitor and a 60hz HDMI edid emulator (I can't use 120hz at the resolution I need).

Here's how the process works at the moment:

DisplayCapture ---> FRC component ---> Sunshine Color Convertor.

DC Init:
`    // Create the DisplayCapture component
    result = amf_factory->CreateComponent(context, AMFDisplayCapture, &(captureComp));
    if (result != AMF_OK) {
      BOOST_LOG(error) << "CreateComponent(AMFDisplayCapture) failed: "sv << result;
      return -1;
    }

    // Set parameters for non-blocking capture
    captureComp->SetProperty(AMF_DISPLAYCAPTURE_MONITOR_INDEX, output_index);
    captureComp->SetProperty(AMF_DISPLAYCAPTURE_FRAMERATE, AMFConstructRate(config.framerate/2, 1));
    BOOST_LOG(info) << "Framerate requested: " << config.framerate;

    captureComp->SetProperty(AMF_DISPLAYCAPTURE_MODE, AMF_DISPLAYCAPTURE_MODE_GET_CURRENT_SURFACE);
    captureComp->SetProperty(AMF_DISPLAYCAPTURE_DUPLICATEOUTPUT, false);`

FRC init:

`    result = amf_factory->CreateComponent(context, AMFFRC, &(frcComp));
    if (result != AMF_OK) {
      BOOST_LOG(error) << "CreateComponent(AMFFRC) failed: "sv << result;
      return -1;
    }

    frcComp->SetProperty(AMF_FRC_ENGINE_TYPE, FRC_ENGINE_DX11);
    frcComp->SetProperty(AMF_FRC_MODE, FRC_ONLY_INTERPOLATED);
    frcComp->SetProperty(AMF_FRC_ENABLE_FALLBACK, false);
    frcComp->SetProperty(AMF_FRC_INDICATOR, true);
    frcComp->SetProperty(AMF_FRC_PROFILE, FRC_PROFILE_SUPER);
    frcComp->SetProperty(AMF_FRC_MV_SEARCH_MODE, FRC_MV_SEARCH_NATIVE);`

Now, my goal is to interpolate 60 fps to 120 and when streaming to my 120hz monitor, I notice the increased smoothness when moving windows around. Using the same settings on the 60hz dongle, this smoothness is absent. **Why could that be? Is refresh rate a factor?** I also theorize I'm not actually seeing 120fps but blurriness in the interpolated frames...

Also, for the AMF_FRC_MODE, I expected to see the increased smoothness when using FRC_ON, but that's not the case. Of course I might be missing something but **what mode should I use to double my framerate?**

And I expected the FRC component to complain when querying output if there's not enough frames, but 1 fed frame outputs 1 converted frame. I expected that it would expect at least 2 input frames and have 3 output frames, but there's only ever 1 frame in the output queue.

Could you please clarify?

**Comment by MikhailAMD** [comment]
Hi,
Few points: 
1. FRC should double frame rate, the rest: presentation, vsync is up to the app. If you convert 60 to 120Hz but watch on 60Hz monitor, you will not see half of the frames. Not sure how can you see on the dongle.
2. Your capture configuration uses GET_CURRENT_SURFACE. This means that Sunshine is responsible for keeping frame rate. It is OK, but if you use KEEP_FRAMERATE the time pacing will be kept by AMF DisplayCapture. It is quite accurate.
3. For FRC you set: FRC_ONLY_INTERPOLATED. It will not double output frames. For that you need to use FRC_x2_PRESENT. It would better work with capture. You would not need to keep captured frame for some time. 
4. Note, that FRC doesn't manage time/pacing. It just renders and produces frames.

**Comment by radugrecu97** [comment]
1. When utilizing Desktop Duplication in Sunshine, refresh rate doesn't matter. It is still streaming 120 frames.

3a. I tried FRC_ONLY_INTERPOLATED & GET_CURRENT_SURFACE with displaying original captured frames and it seems to have worked.

3b. The documentation for FRC_x2_PRESENT states:

`AMF_REPEAT will be returned for the QueryOutput() call with each source frame. **The caller needs to call the FRC component with the same source frame again to get x2 frame rate.**`

What does the bold part mean? The way I understand is that I need to SubmitInput twice with the same surface but I can't because the queue depth is 1 in all FRC configurations from my testing.

And, am I supposed to stream frames only from FRC QueryOutput or from DisplayCapture QueryOutput as well?

4. "It would better work with capture. You would not need to keep captured frame for some time." I don't understand what this means. Could you please elaborate?

**Comment by MikhailAMD** [comment]
1. Yes, this is the correct sequence:
capture->QueryOutput()
frc->SubmitInput()
frc->QueryOutput()
process/submit for encode frame 1
frc->QueryOutput()
process/submit for encode frame 2
Ideally poll or wait for encoder in a separate thread.
3. Why better:
- capture will not capture next frame/surface till the captured is returned. If you use FRC_ONLY_INTERPOLATED, you need to keep captured surface till interpolated is returned and processed/encoded and then submit captured surface for the same. FRC_x2_PRESENT will make a copy and return captured surface ASAP. If your processing time is fast enough, it doesn't matter. But if you want that capture+FRC+CSC shaders run in parallel with encoder, you need to return captured frame ASAP and run polling of encoder in a separate thread.

**Comment by radugrecu97** [comment]
In theory, if everything is working right. Should I be able to see testufo.com correctly?

**Comment by MikhailAMD** [comment]
Yes and no. I believe browser presents video frames with Present(1). Meaning - wait for VSYNC. If video is played in a window (not true full-screen) it doesn't matter much as DWM will do windows composition and presents again with 1 - wait for VSYNC. So we deal with three close to 60fps frequencies : video present, DWM present, capture. They are not synchronized so there is no guarantee that capture will get every video frame. If you want such, you should use "PRESENT" capture mode It will get every DWM present event. But than capture framerate will be variable and driven by DWM. Can fall to 1 fps.
This is all before we add FRC to equation.

**Comment by radugrecu97** [comment]
```
    amf::AMFSurfacePtr capturedFrame = nullptr, output = nullptr;
    D3D11_TEXTURE2D_DESC desc;

    AMF_RESULT result;

    if (dup.capturedSurface != nullptr)
    {
      output = dup.capturedSurface;
      dup.capturedSurface = nullptr;
    }
    else
    {
      // BOOST_LOG(debug) << "### R.G. loop";
      auto capture_status = dup.next_frame(timeout, (amf::AMFData **) &capturedFrame);
      if (capture_status != capture_e::ok) {
        return capture_status;
      }

      // Pass the frame to frame convertor
      result = dup.frcComp->SubmitInput(capturedFrame);

      if (result == AMF_INPUT_FULL || result == AMF_DECODER_NO_FREE_SURFACES)
      {
        BOOST_LOG(debug) << "### R.G. Couldn't submit input to FRC";
      }
      else if (result == AMF_INVALID_FORMAT || result == AMF_INVALID_DATA_TYPE)
      {
        BOOST_LOG(debug) << "### R.G. Input and Output formats don't match. Reinit";
        return capture_e::reinit;
      }
      else if (result != AMF_OK) {
        BOOST_LOG(debug) << "### R.G. ERROR SubmitInput(): " << result;
        return capture_e::reinit;
      }

      result = dup.frcComp->QueryOutput((amf::AMFData**) &output);

      result = dup.frcComp->QueryOutput((amf::AMFData**) &dup.capturedSurface);
    }
```

Here's what I have so far and maybe it's working? I would expect that when I move the windows on the desktop, I'd see 120 fps smoothness but I don't.

And in-game, it made me realize that 60fps looks pretty damn good at 120 hz haha, so it's actually difficult to tell.

**Comment by MikhailAMD** [comment]
Looks OK, but I don't know what happens after. You can try to enable FRC indicator, just to see if it is working: AMF_FRC_INDICATOR = true.
You can dump FRC output and analyze it later:  use AMFDump interface to configure AMFComponent to dump input or/and output.
Another thing: can you try to switch to DX12 - capture, FRC, encoder?

**Comment by radugrecu97** [comment]
> Looks OK, but I don't know what happens after. You can try to enable FRC indicator, just to see if it is working: AMF_FRC_INDICATOR = true.
> You can dump FRC output and analyze it later:  use AMFDump interface to configure AMFComponent to dump input or/and output.
> Another thing: can you try to switch to DX12 - capture, FRC, encoder?

I'll send branch location later.

I'll try dumping. 👍

Sunshine utilities dx11. Setting FRC to use dx12 resulted in a choppy output.


I've tested a few minutes with the code above and occasionally the stream becomes choppy.

Should I loop FRC query until destination variable is non-nullptr?

**Comment by MikhailAMD** [comment]
No need for looping, FRC is synchronous, one input produces two outputs.

**Comment by radugrecu97** [comment]
AMD init and DisplayCapture frame capture: https://github.com/radugrecu97/Sunshine/blob/8310710e0aab5d7e47d453e89d46b6419977e46b/src/platform/windows/display_amd.cpp

Frame processing: https://github.com/radugrecu97/Sunshine/blob/8310710e0aab5d7e47d453e89d46b6419977e46b/src/platform/windows/display_vram.cpp#L1654


FRC INDICATOR doesn't show up in x2_Present with the code code on the branch

**Comment by radugrecu97** [comment]
Also, I was testing DX12 engine for FRC again and noticed that in FRC_x2_PRESENT mode, DisplayCapture captures the wrong surface size (something like 3x523, numbers don't seem logical), which we handle by reinitializing the whole module. Hence the choppiness.

**Comment by MikhailAMD** [comment]
OK, few points from code you provided:
1. The app shares ID3D11DeviceContext with AMF.  The protection you have for device_ctx with a mutex should be applied to capture->QueryOutput call and to frc->QueryOutput.
2. Using CopyResource would probably ease your application development but adds unnecessary load on GFX. You can use AMF-returned textures directly till you release corresponding AMFSurface objects.
3. I don't think issues above affect FRC behavior. I would start with dumps. 
4. Also we plan to add SimpleFRC sample that could be used to test FRC but I will not happen till next big release. 
5. I asked to test DX12 as we may have some quality issue in DX11 path, investigating right now. But basics should still work. 
6. The wrong capture size for DX12 is unexpected. If you want to experiment with DX11 or DX12 with manageable code size, you can use AMF DVR sample. It is probably easy to add FRC there and then share the changed version with me.  This way I can debug if the problem can be reproduced in the modified sample.

**Comment by radugrecu97** [comment]
So, the indicator only appears for me with AMF_FRC_USE_FUTURE_FRAME enabled.

1. Can I use LockDX11 and unlock for that?

I'll follow up on the rest.

**Comment by MikhailAMD** [comment]
Yes, I will ask why the indicator works this way.
You can use AMF LockDX11/UnlockDX11 but it must be used across your app. All these functions do is to Enter and Leave Win32 critical section. If your app uses ID3D11DeviceContext in a separate thread, you should use AMF functions as well. 
So either use only AMF locks or use your mutex everywhere.

**Comment by MikhailAMD** [comment]
You can QueryInterface AMFDump interface from any AMF component:
AMFDumpPtr pDump(component);

**Comment by radugrecu97** [comment]
What format is the output file supposed to be?

**Comment by MikhailAMD** [comment]
Based on surface format which you are dumping: 
NV12:  file.nv12
R8G8B8A8: file.rgba., 
YUV420P: file.yuv 
etc. 
It is just uncompressed data. There are many viewers to play such files.
