### ISSUE TITLE
Does amf support gpu accelerated (opencl) encoding for hevc ?

### ISSUE THREAD

**Issue by nalf3in** [GPUOpen-LibrariesAndSDKs/AMF#56]
Well basically what the title say, I would be interested to encode a hevc video stream using my old r9 290 to accelerate tge process.

**Comment by MikhailAMD** [comment]
There are two questions here:
1. Is HEVC encoder supported on older GPUs? No, RX 480, 470, 460 only.
2. Can application mix OpenCL and HEVC encoder? Yes. For effective usage application must:
 - Properly initialize AMF by InitDX11() and then InitOpenCL() 
- allocate encoder input surface as DX11
- Convert it into OpenCL
- Use the surface as output in OpenCL kernel
- call clFinish()
- Convert the surface back to DX11 - to be sure
- Submit the surface to encoder 
Fast interop between DX11 and OpenCL should do the trick
DX9 is also possible.

**Comment by Xaymar** [comment]
This is practically example code on how to use OpenCL with VCE to speed up and stabilize submission times, i have not found a way to speed up querying the output with opencl yet.

[This code initializes the AMF context, initializes the necessary API and then initializes OpenCL:](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/blob/master/Source/amf-h264.cpp#L200-L234)

```
	/// Create an AMF context.
	if (m_AMFFactory->CreateContext(&m_AMFContext) != AMF_OK)
		ThrowExceptionWithAMFError("<" __FUNCTION_NAME__ "> CreateContext failed with error %ls (code %ld).", res);
	/// Initialize to a specific API.
	m_API = Plugin::API::Base::GetAPIByName(p_VideoAPI);
	m_APIAdapter = m_API->GetAdapterById(p_VideoAdapterId & UINT_MAX, (p_VideoAdapterId >> 32) & UINT_MAX);
	m_APIInstance = m_API->CreateInstanceOnAdapter(m_APIAdapter);
	switch (m_API->GetType()) {
		case Plugin::API::Type::Direct3D11:
			m_MemoryType = H264MemoryType::DirectX11;
			res = m_AMFContext->InitDX11(m_API->GetContextFromInstance(m_APIInstance));
			break;
		case Plugin::API::Type::Direct3D9:
			m_MemoryType = H264MemoryType::DirectX11;
			res = m_AMFContext->InitDX9(m_API->GetContextFromInstance(m_APIInstance));
			break;
		case Plugin::API::Type::OpenGL:
			m_MemoryType = H264MemoryType::OpenGL;
			res = m_AMFContext->InitOpenGL(m_API->GetContextFromInstance(m_APIInstance), GetDesktopWindow(), nullptr);
			break;
		case Plugin::API::Type::Host:
			m_MemoryType = H264MemoryType::Host;
			m_OpenCL = false; // OpenCL is not very useful if your surface and target are in host memory.
			break;
	}
	if (res != AMF_OK)
		ThrowExceptionWithAMFError("<" __FUNCTION_NAME__ "> Initializing Video API failed with error %ls (code %ld).", res);

	/// Initialize OpenCL if user selected it.
	if (m_OpenCL) {
		res = m_AMFContext->InitOpenCL(nullptr);
		if (res != AMF_OK)
			ThrowExceptionWithAMFError("<" __FUNCTION_NAME__ "> InitOpenCL failed with error %ls (code %ld).", res);
		m_AMFContext->GetCompute(amf::AMF_MEMORY_OPENCL, &m_AMFCompute);
	}
```

[Later on, the compute object can be used to convert a DX11/DX9/OpenGL surface to OpenCL, copy all data over and then reconvert it back to DX11/DX9/OpenGL.](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/blob/master/Source/amf-h264.cpp#L803-L825)

```
	amf::AMFSurfacePtr pSurface = nullptr;
	if (m_OpenCL) {
		amf_size l_origin[] = { 0, 0, 0 };
		amf_size l_size0[] = { m_FrameSize.first, m_FrameSize.second, 1 };
		amf_size l_size1[] = { m_FrameSize.first >> 1, m_FrameSize.second >> 1, 1 };

		res = m_AMFContext->AllocSurface(Utility::MemoryTypeAsAMF(m_MemoryType),
			Utility::SurfaceFormatAsAMF(m_ColorFormat),
			m_FrameSize.first, m_FrameSize.second, &pSurface);
		if (res != AMF_OK) // Unable to create Surface
			ThrowExceptionWithAMFError("AllocSurface failed with error %ls (code %d).", res);

		amf::AMFComputeSyncPointPtr pSyncPoint;
		m_AMFCompute->PutSyncPoint(&pSyncPoint);
		pSurface->Convert(amf::AMF_MEMORY_OPENCL);
		m_AMFCompute->CopyPlaneFromHost(frame->data[0], l_origin, l_size0, frame->linesize[0], pSurface->GetPlaneAt(0), false);
		m_AMFCompute->CopyPlaneFromHost(frame->data[1], l_origin, l_size1, frame->linesize[1], pSurface->GetPlaneAt(1), false);
		m_AMFCompute->FinishQueue();
		pSurface->Convert(Utility::MemoryTypeAsAMF(m_MemoryType));
		pSyncPoint->Wait();
```

If I understood Mikhail correctly back then, technically you only have to make sure that the surface is copied and converted at the time of submitting the actual frame. So if you have a frame buffer of some amount of frames and can deal with handling this synchronization (PutSyncPoint and SyncPoint->Wait should do it), you can gain some additional submission stability and less impact on framerate.
I did not implement this in my code due to it being an application that requires mostly real time information, so only final color format conversion is done before submit. I also can't rely on the incoming frame sticking around for more than a single frame without copying it.

**Comment by MikhailAMD** [comment]
One note: CopyPlaneFromHost() assumes that input data are in system memory. If you have OpenCL kernel to produce the data you should do it directly by getting OCL native handles: (cl_mem)surface->GetPlaneAt(0)->GetNative() after conversion.

**Comment by MikhailAMD** [comment]
Closing for now
